import './globals.css'
import type { Metadata } from 'next'
import { Inter,Quicksand } from 'next/font/google'

const quickSand= Quicksand({subsets: ['latin']})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quickSand.className}>{children}</body>
    </html>
  )
}
